# Generated by Django 4.2.23 on 2026-10-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColourLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(db_column='UnitID', max_length=20)),
                ('unit_name', models.CharField(db_column='UnitName', max_length=100)),
                ('pr_code', models.CharField(db_column='PrCode', max_length=20)),
                ('pr_name', models.CharField(db_column='PrName', max_length=100)),
                ('item_code', models.CharField(db_column='ItemCode', max_length=20)),
            ],
            options={
                'db_table': 'vColourLoad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('company_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('address3', models.CharField(blank=True, max_length=200, null=True)),
                ('GSTNo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Company_Information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpNo', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginUsers',
            fields=[
                ('LoID', models.CharField(db_column='LoID', max_length=15, primary_key=True, serialize=False)),
                ('LoPassword', models.CharField(db_column='LoPassword', max_length=15)),
                ('LoPrivilege', models.CharField(db_column='LoPrivilege', max_length=15)),
                ('LoCount', models.IntegerField(db_column='LoCount')),
                ('EmpName', models.CharField(db_column='EmpName', max_length=100)),
                ('EmpDepartment', models.CharField(db_column='EmpDepartment', max_length=100)),
                ('EmpNo', models.IntegerField(db_column='EmpNo')),
            ],
            options={
                'db_table': 'VEmpLogin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaColor',
            fields=[
                ('UnitID', models.IntegerField(db_column='UnitID', primary_key=True, serialize=False)),
                ('UnitName', models.CharField(blank=True, db_column='UnitName', max_length=50, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'MaColor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaPack',
            fields=[
                ('UnitID', models.IntegerField(primary_key=True, serialize=False)),
                ('UnitName', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'MaPack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maparty',
            fields=[
                ('PaCode', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('PaType', models.CharField(max_length=15)),
                ('PaName', models.CharField(blank=True, max_length=50, null=True)),
                ('PaStatus', models.CharField(max_length=20)),
                ('PaAddress', models.CharField(max_length=200)),
                ('PaAddress3', models.CharField(max_length=100)),
                ('PaCreditTerms', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'MaParty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaProduct',
            fields=[
                ('PrCode', models.IntegerField(db_column='PrCode', primary_key=True, serialize=False)),
                ('PrName', models.CharField(db_column='PrName', max_length=300)),
                ('PrUOM', models.CharField(blank=True, max_length=5, null=True)),
                ('PrRate', models.FloatField(blank=True, null=True)),
                ('PrStatus', models.CharField(blank=True, max_length=10, null=True)),
                ('TaxType', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'MaProduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaTax',
            fields=[
                ('TaxType', models.CharField(db_column='TaxType', max_length=20, primary_key=True, serialize=False)),
                ('NOB', models.CharField(blank=True, db_column='NOB', max_length=10, null=True)),
                ('ExciseDuty', models.FloatField(blank=True, db_column='ExciseDuty', null=True)),
                ('EDCaption', models.CharField(blank=True, db_column='EDCaption', max_length=20, null=True)),
                ('CESS', models.FloatField(blank=True, db_column='CESS', null=True)),
                ('CESSCaption', models.CharField(blank=True, db_column='CESSCaption', max_length=20, null=True)),
                ('SalesTax', models.FloatField(blank=True, db_column='SalesTax', null=True)),
                ('STCaption', models.CharField(blank=True, db_column='STCaption', max_length=20, null=True)),
                ('ServiceTax', models.FloatField(blank=True, db_column='ServiceTax', null=True)),
                ('SerTCaption', models.CharField(blank=True, db_column='SerTCaption', max_length=20, null=True)),
                ('SurCharge', models.FloatField(blank=True, db_column='SurCharge', null=True)),
                ('SCCaption', models.CharField(blank=True, db_column='SCCaption', max_length=20, null=True)),
                ('VAT', models.FloatField(blank=True, db_column='VAT', null=True)),
                ('VATCaption', models.CharField(blank=True, db_column='VATCaption', max_length=20, null=True)),
                ('SHCess', models.FloatField(blank=True, db_column='SHCess', null=True)),
                ('SHCessCaption', models.CharField(blank=True, db_column='SHCessCaption', max_length=20, null=True)),
                ('FormReq', models.CharField(blank=True, db_column='FormReq', max_length=3, null=True)),
                ('FormName', models.CharField(blank=True, db_column='FormName', max_length=15, null=True)),
                ('Status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('Type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
            ],
            options={
                'db_table': 'MaTax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ProductColour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RptRateLoad',
            fields=[
                ('PrCode', models.CharField(max_length=50)),
                ('InvSpecification', models.CharField(max_length=200)),
                ('InvParticular', models.CharField(max_length=200)),
                ('InvRate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('InvQty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('InvNo', models.IntegerField(primary_key=True, serialize=False)),
                ('InvYearCode', models.IntegerField()),
                ('PaCode', models.CharField(max_length=50)),
                ('InvEmpNo', models.IntegerField()),
            ],
            options={
                'db_table': 'rptRateLoad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrInvoiceMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invno', models.CharField(db_column='InvNo', max_length=50)),
                ('invyearcode', models.CharField(db_column='InvYearCode', max_length=20)),
                ('invtype', models.CharField(db_column='InvType', max_length=20)),
                ('pacode', models.CharField(db_column='Pacode', max_length=50)),
                ('invdate', models.DateField(db_column='InvDate')),
                ('invgrandtotal', models.FloatField(db_column='InvGrandTotal', default=0)),
                ('invempno', models.IntegerField(db_column='InvEmpNo')),
                ('einvstatus', models.CharField(blank=True, db_column='Einvstatus', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TrInvoiceMain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrOpeningBalNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacode', models.CharField(db_column='Pacode', max_length=50)),
                ('invamt', models.FloatField(db_column='InvAmt', default=0)),
                ('invempno', models.IntegerField(db_column='InvEmpNo')),
                ('entrydate', models.DateField(db_column='EntryDate')),
                ('invdate', models.DateField(blank=True, db_column='InvDate', null=True)),
            ],
            options={
                'db_table': 'TrOpeningBalNew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrPayCollMain',
            fields=[
                ('payentryno', models.CharField(db_column='PayEntryNo', max_length=50, primary_key=True, serialize=False)),
                ('payyearcode', models.CharField(db_column='PayYearCode', max_length=20)),
                ('paydate', models.DateField(db_column='PayDate')),
            ],
            options={
                'db_table': 'TrPayCollMain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrPayCollSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payentryno', models.CharField(db_column='PayEntryNo', max_length=50)),
                ('payyearcode', models.CharField(db_column='PayYearCode', max_length=20)),
                ('invno', models.CharField(db_column='InvNo', max_length=50)),
                ('invyearcode', models.CharField(db_column='InvYearCode', max_length=20)),
                ('invtype', models.CharField(db_column='InvType', max_length=20)),
                ('payamount', models.FloatField(db_column='PayAmount', default=0)),
            ],
            options={
                'db_table': 'TrPayCollSub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsoMain',
            fields=[
                ('soNo', models.IntegerField(primary_key=True, serialize=False)),
                ('soYearCode', models.CharField(max_length=9)),
                ('soDate', models.DateTimeField(blank=True, null=True)),
                ('PaCode', models.CharField(blank=True, max_length=7, null=True)),
                ('PaCreditTerms', models.CharField(blank=True, max_length=100, null=True)),
                ('SoPreparedTime', models.DateTimeField(blank=True, null=True)),
                ('soEmpNo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TrsoMain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsoMainHistory',
            fields=[
                ('soNo', models.IntegerField(primary_key=True, serialize=False)),
                ('soYearCode', models.CharField(max_length=9)),
                ('soDate', models.DateTimeField(blank=True, null=True)),
                ('PaCode', models.CharField(blank=True, max_length=7, null=True)),
                ('PaCreditTerms', models.CharField(blank=True, max_length=100, null=True)),
                ('SoPreparedTime', models.DateTimeField(blank=True, null=True)),
                ('soEmpNo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TrsoMain_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsoSub',
            fields=[
                ('soSlNo', models.IntegerField()),
                ('soYearCode', models.CharField(max_length=9)),
                ('PrCode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('soSpecification', models.CharField(max_length=250)),
                ('soQty', models.FloatField(blank=True, null=True)),
                ('soRate', models.FloatField(blank=True, null=True)),
                ('soParticular', models.CharField(blank=True, max_length=250, null=True)),
                ('soDiscount', models.FloatField(blank=True, null=True)),
                ('TaxType', models.CharField(blank=True, max_length=50, null=True)),
                ('soTaxAmt', models.FloatField(blank=True, null=True)),
                ('SoDeliveryPreference', models.CharField(blank=True, max_length=100, null=True)),
                ('SoDeliveryDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TrsoSub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsoSubHistory',
            fields=[
                ('soSlNo', models.IntegerField(primary_key=True, serialize=False)),
                ('soYearCode', models.CharField(max_length=9)),
                ('PrCode', models.CharField(max_length=30)),
                ('soSpecification', models.CharField(max_length=250)),
                ('soQty', models.FloatField(blank=True, null=True)),
                ('soRate', models.FloatField(blank=True, null=True)),
                ('soParticular', models.CharField(blank=True, max_length=250, null=True)),
                ('soDiscount', models.FloatField(blank=True, null=True)),
                ('TaxType', models.CharField(blank=True, max_length=50, null=True)),
                ('soTaxAmt', models.FloatField(blank=True, null=True)),
                ('SoDeliveryPreference', models.CharField(blank=True, max_length=100, null=True)),
                ('SoDeliveryDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TrsoSub_History',
                'managed': False,
            },
        ),
    ]
